### PR TITLE
Fix i686 build -Werror=incompatible-pointer-types complaint

### LINKED ISSUE #28: fails to build on 32 bit
The build on 32 bit archlinux fails due to some type cast from `size_t *` to `long unsigned int *`:

```
+ exec meson setup --prefix /usr --libdir /usr/lib --libexecdir /usr/lib --bindir /usr/bin --sbindir /usr/bin --includedir /usr/include --datadir /usr/share --mandir /usr/share/man --infodir /usr/share/info --localedir /usr/share/locale --sysconfdir /etc --localstatedir /var --sharedstatedir /var/lib --buildtype release --auto-features enabled --wrap-mode nofallback -D b_lto=true build grim
The Meson build system
Version: 0.48.2
Source dir: /build/grim/src/grim
Build dir: /build/grim/src/build
Build type: native build
Project name: grim
Project version: 0.0.0
Appending CFLAGS from environment: '-march=i686 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt'
Appending LDFLAGS from environment: '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now'
Appending CPPFLAGS from environment: '-D_FORTIFY_SOURCE=2'
Native C compiler: cc (gcc 8.2.1 "cc (GCC) 8.2.1 20180831")
Build machine cpu family: x86
Build machine cpu: i686
Found pkg-config: /usr/bin/pkg-config (1.5.4)
Dependency cairo found: YES 1.16.0
Dependency wayland-client found: YES 1.16.0
Dependency wayland-protocols found: YES 1.16
Dependency libjpeg found: YES 2.0.0
Library m found: YES
Program wayland-scanner found: YES (/usr/bin/wayland-scanner)
Program scdoc found: NO
Build targets in project: 2
Option werror is: True [default: true]
Found ninja-1.8.2 at /usr/bin/ninja
ninja: Entering directory `build'
[1/16] Generating 'protocol/protocol@@client_protos@sta/wlr-screencopy-unstable-v1-protocol.c'.
[2/16] Generating 'protocol/protocol@@client_protos@sta/xdg-output-unstable-v1-protocol.c'.
[3/16] Generating 'protocol/protocol@@client_protos@sta/xdg-output-unstable-v1-client-protocol.h'.
[4/16] Generating 'protocol/protocol@@client_protos@sta/wlr-screencopy-unstable-v1-client-protocol.h'.
[5/16] Generating 'grim@exe/wlr-screencopy-unstable-v1-client-protocol.h'.
[6/16] Generating 'grim@exe/xdg-output-unstable-v1-client-protocol.h'.
[7/16] Compiling C object 'protocol/protocol@@client_protos@sta/meson-generated_wlr-screencopy-unstable-v1-protocol.c.o'.
[8/16] Compiling C object 'protocol/protocol@@client_protos@sta/meson-generated_xdg-output-unstable-v1-protocol.c.o'.
[9/16] Linking static target protocol/libclient_protos.a.
[10/16] Compiling C object 'grim@exe/box.c.o'.
[11/16] Compiling C object 'grim@exe/cairo_jpg.c.o'.
FAILED: grim@exe/cairo_jpg.c.o 
cc -Igrim@exe -I. -I../grim -I../grim/include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/uuid -flto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -O3 -Wno-unused-parameter -march=i686 -mtune=generic -O2 -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2  -MD -MQ 'grim@exe/cairo_jpg.c.o' -MF 'grim@exe/cairo_jpg.c.o.d' -o 'grim@exe/cairo_jpg.c.o' -c ../grim/cairo_jpg.c
../grim/cairo_jpg.c: In function ‘cairo_surface_write_to_jpeg_mem’:
../grim/cairo_jpg.c:50:30: error: passing argument 3 of ‘jpeg_mem_dest’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  jpeg_mem_dest(&cinfo, data, len);
                              ^~~
In file included from ../grim/cairo_jpg.c:13:
/usr/include/jpeglib.h:922:43: note: expected ‘long unsigned int *’ but argument is of type ‘size_t *’ {aka ‘unsigned int *’}
                            unsigned long *outsize);
                            ~~~~~~~~~~~~~~~^~~~~~~
../grim/cairo_jpg.c: In function ‘cj_write’:
../grim/cairo_jpg.c:83:42: error: comparison of integer expressions of different signedness: ‘ssize_t’ {aka ‘int’} and ‘unsigned int’ [-Werror=sign-compare]
  if (write((long) closure, data, length) < length) {
                                          ^
cc1: all warnings being treated as errors
[12/16] Compiling C object 'grim@exe/buffer.c.o'.
[13/16] Compiling C object 'grim@exe/main.c.o'.
ninja: build stopped: subcommand failed.
```

regards,
deep-42-thought

### PR DESCRIPTION
**Pull request by jnpkrn**
This was caused with jpeg_mem_dest expecting pointer to unsigned long
and being fed with pointer to size_t, which may amount to different
data-width types.  There's also a simple overflow check for such
cases now.

Fixes #28

### CODE REVIEW

**Comment by jnpkrn** [comment]
Forgot to update the header file ... done.

File: cairo_jpg.c [hunk 1]
```diff
@@ -91,18 +92,18 @@ cairo_status_t cairo_surface_write_to_jpeg_stream(cairo_surface_t *sfc,
...
 	unsigned char *data = NULL;
-	size_t len = 0;
+	unsigned long len = 0;
 
 	e = cairo_surface_write_to_jpeg_mem(sfc, &data, &len, quality);
-	if (e != CAIRO_STATUS_SUCCESS) {
-		return e;
-	}
+	if (e == CAIRO_STATUS_SUCCESS) {
+		e = len && (len - 1) > (UINT_MAX - 1)
```
Comment (emersion) [inline cairo_jpg.c]: Why not change `len` to be `unsigned int` instead?

Additionally, can you rewrite this code not to use a ternary operator?

Comment (jnpkrn) [reply cairo_jpg.c]: Hmm, that's mostly a (corner case) discrepancy of two APIs where
there's a mismatch on type under some circumstances.  In such cases
I'd prefer to keep overflow check in place (now rewritten as an
assertion, is it better?), but for that to be possible, it has to be
deferred under current arrangement, since pass-by-address would drop
that immeditely.  There are many ways to deal with that, primary
objective is not to resort to not using `-Werror`.

File: cairo_jpg.c [hunk 2]
```diff
@@ -91,18 +93,17 @@ cairo_status_t cairo_surface_write_to_jpeg_stream(cairo_surface_t *sfc,
...
 	cairo_status_t e;
 	unsigned char *data = NULL;
-	size_t len = 0;
+	unsigned long len = 0;
 
 	e = cairo_surface_write_to_jpeg_mem(sfc, &data, &len, quality);
-	if (e != CAIRO_STATUS_SUCCESS) {
-		return e;
+	if (e == CAIRO_STATUS_SUCCESS) {
+		assert(sizeof(unsigned long) <= sizeof(size_t)
```
Comment (emersion) [inline cairo_jpg.c]: Hmm, I don't get why this assertion is still required. `len` is `unsigned long` and `cairo_write_func_t` takes an  `unsigned long`… Am I missing something?

**Comment by emersion** [comment]
Thanks!

**Comment by jnpkrn** [comment]
Sorry for delay in response, I was actually looking at the original
code repo I didn't know about previously:
  https://github.com/rahra/cairo_jpg
and wanted to start discussion there since IIRC this problem
could be traced there as well at its current form.

Will definitely let you know if/when that happens.
